# Generated by Django 3.2 on 2022-06-23 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crypto',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('symbol', models.CharField(max_length=10)),
                ('rank', models.SmallIntegerField()),
                ('category', models.CharField(max_length=255)),
                ('slug', models.CharField(max_length=255)),
                ('logo', models.CharField(max_length=255)),
                ('quote', models.IntegerField()),
                ('max_supply', models.IntegerField()),
                ('circulating_supply', models.IntegerField()),
                ('total_supply', models.IntegerField()),
                ('tags', models.TextField()),
            ],
        ),
    ]
