# Generated by Django 3.2 on 2022-06-23 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crypto',
            name='circulating_supply',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='crypto',
            name='quote',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='crypto',
            name='total_supply',
            field=models.FloatField(),
        ),
    ]
