# Generated by Django 3.2 on 2022-06-23 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptos', '0002_auto_20220623_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crypto',
            name='max_supply',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
